//
//
// File generated from our OpenAPI spec
//
//

package stripe

import (
	"context"
)

// v1InvoiceRenderingTemplateService is used to invoke /v1/invoice_rendering_templates APIs.
type v1InvoiceRenderingTemplateService struct {
	B   Backend
	Key string
}

// Retrieves an invoice rendering template with the given ID. It by default returns the latest version of the template. Optionally, specify a version to see previous versions.
func (c v1InvoiceRenderingTemplateService) Retrieve(ctx context.Context, id string, params *InvoiceRenderingTemplateRetrieveParams) (*InvoiceRenderingTemplate, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Updates the status of an invoice rendering template to ‘archived' so no new Stripe objects (customers, invoices, etc.) can reference it. The template can also no longer be updated. However, if the template is already set on a Stripe object, it will continue to be applied on invoices generated by it.
func (c v1InvoiceRenderingTemplateService) Archive(ctx context.Context, id string, params *InvoiceRenderingTemplateArchiveParams) (*InvoiceRenderingTemplate, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Unarchive an invoice rendering template so it can be used on new Stripe objects again.
func (c v1InvoiceRenderingTemplateService) Unarchive(ctx context.Context, id string, params *InvoiceRenderingTemplateUnarchiveParams) (*InvoiceRenderingTemplate, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// List all templates, ordered by creation date, with the most recently created template appearing first.
func (c v1InvoiceRenderingTemplateService) List(ctx context.Context, listParams *InvoiceRenderingTemplateListParams) *V1List[*InvoiceRenderingTemplate] {
	_ = "STUB: not implemented"
	return nil
}
